added README update workflow
ComputerSocietyVITC/Annual-Yearbook pull request #17
Opened 2022-10-08 17:31 UTC by 0b51d14n217

2022-10-08 18:00 UTC, AbhijithGanesh commented
@0b51d14n217 Please add a description to the Pull Request, Empty pull request is confusing often😅!

2022-10-08 18:04 UTC, 0b51d14n217 commented
> @0b51d14n217 Please add a description to the Pull Request, Empty pull request is confusing often😅!

Sure, updated Pull Request.

2022-10-08 18:12 UTC, AbhijithGanesh requested changes

2022-10-08 18:12 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> +    - uses: 0b51d14n217/Annual-Yearbook@readme-workflow
```suggestion
 - run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }})
```

2022-10-08 18:12 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> +    - uses: 0b51d14n217/Annual-Yearbook@readme-workflow
This basically tells the action to run it in a particular manner!

2022-10-08 18:12 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> +        AVATAR_SHAPE: 'round'
These are data points, we should rather focus on automating it! The COMMIT_MESSAGE is good though

2022-10-08 18:28 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> + - run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }})
You need to call it Change Readme by @$...
```suggestion
 - run-name: Changes to Readme - ${{ inputs.deploy_target }} by @${{ github.actor }})
```

2022-10-08 18:53 UTC, cool-pants commented
@0b51d14n217 could you squash the last two commits to have a cleaner commit history?
Otherwise the content seems fine 👍.

2022-10-09 06:46 UTC, AbhijithGanesh requested changes

2022-10-09 06:46 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> + - run-name: Changes to Readme - ${{ inputs.deploy_target }} by @${{ github.actor }})
The indentation seems to be incorrect here😀 ! YAML is an indented file system!

2022-10-09 06:46 UTC, AbhijithGanesh commented on .github/workflows/readmeupdate.yaml
> + - run-name: Changes to Readme - ${{ inputs.deploy_target }} by @${{ github.actor }})
```suggestion
    - uses: actions/checkout@v2
    - run-name: Changes to Readme - ${{ inputs.deploy_target }} by @${{ github.actor }})
```

2022-10-09 07:09 UTC, closed without merging

2022-10-09 07:09 UTC, AbhijithGanesh commented
Closed on request by @0b51d14n217